### ISSUE TITLE
cuda_helpers.h:23:28: fatal error: cuda_jetbrains.h: No such file or directory

### ISSUE THREAD

**Issue by janiteja** [uber/sbnet#1]
Hi, I have a compilation error. It complains about cuda_jetbrains.h, I couldn't find anything about such a file online. How to resolve this?

**Comment by JunhyeonPark** [comment]
I also have this problem when compiling cuda_helpers.h, 
so I just change (cuda_jetbrains.h -> cuda.h), and make.

**Comment by JunhyeonPark** [comment]
I changed (cuda_jetbrains.h -> cuda.h) in **cuda_helper.h**
and changed **Makefile** like
```diff
 TF_INC   = $(shell python -c "import tensorflow; print(tensorflow.sysconfig.get_include())
+TF_LIB   = $(shell python -c 'import tensorflow; print(tensorflow.sysconfig.get_lib())')
        ...
        ...
        ...
 build/libsbnet.so: $(CUOBJS)
 ln -sf build/libsbnet.so
 mkdir -p build
 g++ -std=c++11 -g -shared \
     sparse_gather.cc reduce_mask.cc \
     -o build/libsbnet.so \`
     build/sparse_gather.cu.o build/reduce_mask.cu.o \
     -I $(TF_INC) \
     -I $(CUDA_INC) \
     -D GOOGLE_CUDA=1 -fPIC -lcudart -L $(CUDA_LIB) $(ABI) \
+    -L $(TF_LIB) -ltensorflow_framework -fopenmp
```

but after building libsbnet.so, make test I have some problem like...




### Configurations:
+ Ubuntu 16.04.3 LTS
+ Python 3.5.2
+ Tensorflow 1.4.1

**Comment by andrei-pokrovsky** [comment]
That was just a dummy header with #defines to make the CLion GUI recognize all the cuda keywords, it wasn't needed. Removed the include.
