### ISSUE TITLE
Is the detection model used in the SBNet paper open?

### ISSUE THREAD

**Issue by dongxiao92** [uber/sbnet#12]
I want to use the model on KITTI LiDAR dataset.
But I only find the test and implementation codes for operators.  
I cannot find the model definition. So I'd like to know  whether the model is open-soureced.

**Comment by andrei-pokrovsky** [comment]
We haven't open sourced the detection model yet, the resnet blocks is the highest level of model we have open sourced so far.

**Comment by dongxiao92** [comment]
@andrei-pokrovsky Thanks
