### ISSUE TITLE
AttributeError: module 'f21c708d1ddc75dcce283dd13fe531f7' has no attribute 'sparse_gather'

### ISSUE THREAD

**Issue by dhingratul** [uber/sbnet#14]
File "/sbnet_tensorflow/benchmark/sparse_conv_lib.py", line 123, in _sparse_scatter_grad
    dout_dx = sbnet_module.sparse_gather(
AttributeError: module 'f21c708d1ddc75dcce283dd13fe531f7' has no attribute 'sparse_gather'

**Comment by andrei-pokrovsky** [comment]
Hi, what's your system configuration including hw/os/software versions?

**Comment by dhingratul** [comment]
Ubuntu 16.04, Cuda 9/cudnn 7.1, GTX 1080Ti Dual, tensorflow (pip) = 1.8.0

**Comment by dhingratul** [comment]
This is reproducible with TF 1.2 version/ Cuda 8-0, from the older commits in the repository.

**Comment by dhingratul** [comment]
There was an issue with a broken symlink, as ```make clean``` doesn't remove the symlink. Hence re-running ```make``` creates a broken symlink for some reason.
