### ISSUE TITLE
Performance for sparse_scatter_var worse not always better than sparse_scatter 

### ISSUE THREAD

**Issue by dhingratul** [uber/sbnet#17]
The description says using mutable tensors(tf.Variable) would be more efficient because of in-place copy, but the perf degrades using sparse_scatter_var as opposed to sparse_scatter in some of the scenarios with the difference in input size to the Sbnet block. What is the tradeoff for using it ?

**Comment by andrei-pokrovsky** [comment]
I'm afraid this is not specific enough for a repro. How are you benchmarking your code? Are you using cuda events for timing?

**Comment by dhingratul** [comment]
I actually profiled compared my time profiles from tensorflow's Timeline and just timing the sess.run block, the timings were very similar, hence in this case I timed it just using a time.time() call. I can double check with Timeline to make sure.
