### ISSUE TITLE
No gradient defined for SparseScatter_Var

### ISSUE THREAD

**Issue by dhingratul** [uber/sbnet#20]
Trying to reproduce the paper's result with the recommended sparse_scatter_var method, but I am getting an error which says the gradients are not registered
`LookupError: No gradient defined for operation 'network/SparseScatterVar' (op type: SparseScatterVar)
`

**Comment by andrei-pokrovsky** [comment]
Also, sparse_scatter_var is only intended for inference. We didn't apply these optimizations for training. During inference you shouldn't need the gradient.

**Comment by dhingratul** [comment]
Did you create different training/inference graphs or re-use weights from the training step during inference within the same graph?

**Comment by andrei-pokrovsky** [comment]
IIRC we recreated the graph during inference with minor differences (BN is_training=False, sparse_scatter_var). The weights were imported from learned weights during training of course (unless i'm misunderstanding your question).
