### ISSUE TITLE
Huge loss in accuracy using SBNet

### ISSUE THREAD

**Issue by dhingratul** [uber/sbnet#24]
I was able to see the claimed speedup in terms of inference times, but there is a huge loss in terms of accuracy. Please see a simple MNIST example where I artificially created the images and masks. I am seeing a precision of about 11% which is as good as random guessing with a 10 class problem. I also tried to train the algorithm longer, but the precision saturates at about 11%. Without using SbNet you can get to a precision of ~80% after a few epochs. 

[MNIST_sbnet_repr.py.tar.gz](https://github.com/uber/sbnet/files/2337932/MNIST_sbnet_repr.py.tar.gz)

**Comment by andrei-pokrovsky** [comment]
I recommend first trying to reproduce your network results with 0 sparsity (fully dense network) implemented using sbnet. With that approach the results should be identical but if it doesn't work it would indicate there's a bug in your implementation. This way you can bisect the debugging.

**Comment by andrei-pokrovsky** [comment]
Glad to hear you were able to observe the expected speedup.

**Comment by dhingratul** [comment]
Yes, I am able to recover the results with fully dense sparsity mask, but not with sparse masks.
