### ISSUE TITLE
is there a pytorch version?

### ISSUE THREAD

**Issue by mjjdick** [uber/sbnet#27]
Hi, I just want to know is there any pytorch version operation of sbnet?

**Comment by libohit** [comment]
@mjjdick  have you find the pytorch implementation about SBNet operation?

**Comment by jin-s13** [comment]
Same question.

**Comment by Jee-King** [comment]
@mjjdick @libohit @jin-s13 
Hi, have you found the pytorch implementation about SBNet?

**Comment by gitauron** [comment]
@mjjdick @libohit @jin-s13 @Jee-King 
Is there any update regarding a pytorch version of SBNet? Thanks
