### ISSUE TITLE
There is a "TypeError" when I run benchmarks execute.

### ISSUE THREAD

**Issue by earlysleepearlyup** [uber/sbnet#5]
**I have `make` and `make test` passed.**

**When I run this command:**
`cd sbnet_tensorflow/benchmarks && ./run_all_behchmarks.bash`

**Error:**
TypeError: Input 'active_block_indices' of 'SparseGather' Op has type int64 that does not match expected type of int32.
TypeError: Input 'active_block_indices' of 'SparseGather' Op has type int64 that does not match expected type of int32.
  File "/home/znjs/sbnet-master/sbnet_tensorflow/benchmark/sparse_conv_lib.py", line 542, in sparse_conv2d_custom
    transpose=transpose)
  File "<string>", line 39, in sparse_gather
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 513, in apply_op
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'active_block_indices' of 'SparseGather' Op has type int64 that does not match expected type of int32.
TypeError: Input 'active_block_indices' of 'SparseGather' Op has type int64 that does not match expected type of int32.

**Ubuntu 14.04** 
**GTX 1050Ti**
**tensorflow 1.2.1**
**Python 2.7.6**
**CUDA 8.0**
**cuDNN 5.1**

**Comment by andrei-pokrovsky** [comment]
Thank you for reporting. Fixed in 7f697b4c35fe2d93522932e211071cfd8eae3944

**Comment by earlysleepearlyup** [comment]
@andrei-pokrovsky Thank you for so exhaustive comments.it works very well.
