### ISSUE TITLE
3D LiDAR Dataset

### ISSUE THREAD

**Issue by earlysleepearlyup** [uber/sbnet#6]
If you can provide me with 3D LiDAR Dataset, I would be greatly appreciated.

**Comment by andrei-pokrovsky** [comment]
In the near-term open-sourcing our internal LIDAR dataset is outside of the scope of this project unfortunately. Longer term please stay tuned for announcements from Uber ATG :)

**Comment by earlysleepearlyup** [comment]
@andrei-pokrovsky  That's a pity. Still thank you so much.
